---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: document
  path: src/data/authors.json
  label: Author List
- type: heading
  label: Config
- type: document
  path: config.json
  label: Site Info
upload_dir: src/static
public_path: src/static
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: src/.next
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
